const uuid = require('./uuid');
/**
 * Custom Contants
 *
 * @exports {Object}
 */
module.exports = {
  DEFAULT: 'DEFAULT',
  ROUTE: 'ROUTE',
  VIEW: 'VIEW',
  WEB: 'WEB',
  AGENCY: 'AGENCY',
  EVERYONE: 'EVERYONE',
  ADMIN: 'ADMIN',
  USER: 'USER',
  GIS_TENANT: 'GIS_TENANT',
  GIS_SUPER_ADMIN: 'GIS_SUPER_ADMIN',
  GIS_ADMIN: 'GIS_ADMIN',
  GIS_USER: 'GIS_USER',
  A: 'A',
  B: 'B',
  BIKE: 'BIKE',
  QUOTE: 'QUOTE',
  USER_PROFILE: 'USER_PROFILE',
  ADD_TENANT: 'ADD_TENANT',
  COMPANY_LIST: 'COMPANY_LIST',
  ADD_USER: 'ADD_USER',
  ADD_ROLE: 'ADD_ROLE',
  USER_LIST: 'USER_LIST',
  ROLE_LIST: 'ROLE_LIST',
  EDIT_ROLE: 'EDIT_ROLE',
  BIKE_INSURANCE: 'BIKE_INSURANCE',
  QUOTATION: 'QUOTATION',
  CART: 'CART',
  COMPANY: 'COMPANY',
  DEFAULT_PRIVILEGES: [
    uuid.USER_PROFILE,
    uuid.QUOTATION,
    uuid.CART
  ]
};
