const uuid = require('./uuid');
/**
 * Custom Contants
 *
 * @exports {Object}
 */
module.exports = {
  DEFAULT: 'DEFAULT',
  ROUTE: 'ROUTE',
  VIEW: 'VIEW',
  WEB: 'WEB',
  AGENCY: 'AGENCY',
  EVERYONE: 'EVERYONE',
  ADMIN: 'ADMIN',
  USER: 'USER',
  GIS_TENANT: 'GIS_TENANT',
  GIS_SUPER_ADMIN: 'GIS_SUPER_ADMIN',
  GIS_ADMIN: 'GIS_ADMIN',
  GIS_USER: 'GIS_USER',
  USER_PROFILE: 'USER_PROFILE',
  ADD_TENANT: 'ADD_TENANT',
  ADD_USER: 'ADD_USER',
  ADD_ROLE: 'ADD_ROLE',
  USER_LIST: 'USER_LIST',
  ROLE_LIST: 'ROLE_LIST',
  EDIT_ROLE: 'EDIT_ROLE',
  INSURANCE: 'INSURANCE',
  DEFAULT_PRIVILEGES: [
    uuid.USER_PROFILE
  ]
};
