/**
 * Custom Contants
 *
 * @exports {Object}
 */
module.exports = {
  DEFAULT: 'DEFAULT',
  WEB: 'WEB',
  AGENCY: 'AGENCY',
  EVERYONE: 'EVERYONE',
  ADMIN: 'ADMIN',
  USER: 'USER',
  GIS_TENANT: 'GIS_TENANT',
  GIS_SUPER_ADMIN: 'GIS_SUPER_ADMIN',
  GIS_ADMIN: 'GIS_ADMIN',
  GIS_USER: 'GIS_USER',
  ADD_TENANT: 'ADD_TENANT',
  ADD_USER: 'ADD_USER',
  ADD_ROLE: 'ADD_ROLE',
  USER_LIST: 'USER_LIST',
  ROLE_LIST: 'ROLE_LIST',
  EDIT_ROLE: 'EDIT_ROLE',
  INSURANCE: 'INSURANCE'
};
